# Generated by Django 5.0.6 on 2024-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gorod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=30, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='magaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop', models.CharField(max_length=30, verbose_name='Магазин')),
                ('City', models.CharField(max_length=30, verbose_name='Город')),
                ('Street', models.CharField(max_length=30, verbose_name='Улица')),
                ('Building', models.CharField(max_length=30, verbose_name='Дом')),
                ('Open', models.TimeField(verbose_name='Время открытия')),
                ('Close', models.TimeField(verbose_name='Время закрытия')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='ulica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=30, verbose_name='Улица')),
                ('City', models.CharField(max_length=30, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
    ]
