# Generated by Django 5.0.6 on 2024-07-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magaz',
            name='id_City',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.gorod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magaz',
            name='id_Street',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.ulica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ulica',
            name='id_City',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.gorod'),
            preserve_default=False,
        ),
    ]
